### ISSUE TITLE
Autocreate documentType if none selected during collection create

### ISSUE THREAD

**Issue by ComLock** [enonic/app-explorer#310]
User can select a document type when creating a new collection. If document type is not selected, Explorer should create one automatically. Auto-generate a document type name in this case.

**Comment by ComLock** [comment]
@ase Discovered that Collection Create is still using a service. I would like to convert that to an GraphQL mutation.
Can I do that as part of this issue?

Duplicate, Modify and Delete should also be converted to GraphQL mutations.

**Comment by ComLock** [comment]
Since the auto created documentType name is to be based on the collection name, the collection name needs to have the same limitations as documentType names.

**Comment by alansemenov** [comment]
> Discovered that Collection Create is still using a service. I would like to convert that to an GraphQL mutation.
> Can I do that as part of this issue?
> Duplicate, Modify and Delete should also be converted to GraphQL mutations.

Mutations should be done in a separate issue (several issues actually, one per mutation).
