### ISSUE TITLE
Create new document type button disappears

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-explorer#394]
After it's used once, the "+" icon for creating a new document type disappears. Have to refresh the page to get it back.

**Comment by ComLock** [comment]
It turns out the Sidebar onHide is called both when a dialog is opened AND ALSO when it is closed :(
But none of the other Sidebar events are called (onHidden, onShow, onVisible)

Since I'm not changing the state of the sidebar visibility I think onHide should not have been called at all.
