### ISSUE TITLE
Replace multiple field toggle controls with one

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-explorer#405]
Several Explorer pages have toggle controls in the header, each toggling on/off one field in the table below. This is not very user friendly, so we'll replace it with one toggle control with label "All fields", which will switch between the default set of columns and all columns.

The default state of the "All fields" toggle control should be "off" (showing only default columns). 

Note that for some pages (like "Interfaces") the toggle control is already by default "on" for some columns. This means that these columns should be made a part of the default set of columns and be always shown independent of the new toggle control's state.

Now:
![image](https://user-images.githubusercontent.com/11612490/138837046-86aa1c79-f14a-4ba7-8e0f-ce94c8cc878d.png)

Should be changed to:
![image](https://user-images.githubusercontent.com/11612490/138840480-a31f29c9-34a7-4eab-8d33-18bf1d642e6d.png)
![image](https://user-images.githubusercontent.com/11612490/138858645-aa9f4000-331c-4f34-93d7-b18e01b4c407.png)

**Comment by poi33** [comment]
#429 only does this for documentTypes
Needs to be done for other pages
