### ISSUE TITLE
Remove hover in search result

### ISSUE THREAD

**Issue by ComLock** [enonic/app-explorer#509]
Both sideways and table row

**Comment by poi33** [comment]
@ComLock both the homepage and interface search gives errors when using them. 
How do you show search results? Or how do you use the search field?

**Comment by ComLock** [comment]
Fixed, there seems to have been a bug fixed in the Query DSL. It works in Enonic XP 7.10.0-SNAPSHOT.

**Comment by poi33** [comment]
Do we really want to add a dependency of 7.10.0 to app-explorer @ComLock ?
