### ISSUE TITLE
Improvements to collection form

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#705]
Improve the New/edit collection form by making the following changes:

* change the "Managed document type(s)" label to be "normal" small size
* Change the label currently saying "com.enonic.app.explorer:webcrawl" to be "<collector name> configuration", and if possible remove red strip on top, and make the size a bit smaller (so it is obvious that it is a subset of the "Collector" heading.

**Comment by ComLock** [comment]
What do you mean "normal" small size?

And what about when Collector is none, then it says "Default document type". Still "normal" small size?

![Image](https://user-images.githubusercontent.com/118847/211317331-987171f1-3048-424a-a17b-860ccd781ba6.png)

**Comment by ComLock** [comment]
It's pretty easy to move things around. Here are two variants: I like the latter variant.

![Image](https://user-images.githubusercontent.com/118847/211318637-591cc5a5-8d5a-4107-ad59-b67a5f53dc09.png)

![Image](https://user-images.githubusercontent.com/118847/211320110-293a317f-5f2e-4c39-906c-ee159c385544.png)

**Comment by ComLock** [comment]
Hopefully this is somewhat "normal" small size :)

![Image](https://user-images.githubusercontent.com/118847/211321075-b333f5e2-a113-4dcb-bc3b-c8ae26f22454.png)
![Image](https://user-images.githubusercontent.com/118847/211321076-b2c657a8-d440-491b-b02c-43c58e621792.png)

**Comment by sigdestad** [comment]
the "latter" variant is clearly the best. With one small changes:
* Change the size of the "Managed document types" label to be the same as "url" and "custom user agent". Just a label, no major heading basically.

**Comment by sigdestad** [comment]
Nice touch by inlining the config :-)
