### ISSUE TITLE
Removing collections from the document API

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#808]
Current version of the document API forces the use of a path that contains "collection". This is not flexible, and also be abit cumbersome to document.

To simplify/improve make the following changes:

* Rename the main API path from /webapp/com.enonic.app.explorer/collections/api/v1 to /webapp/com.enonic.app.explorer/documents/api/v1
* Remove the /{collectionname}/documents path from the API
* Add a new parameter "collection" to the methods, so developers can pass the collection name there instead (mandatory field for now)

**Comment by ComLock** [comment]
Or even /api/rest/documents/v1

**Comment by sigdestad** [comment]
I agree path should be /api/documents/v1

**Comment by sigdestad** [comment]
I've spent more time studying this, we should perhaps keep the collection name in the path when doing POST, GET (a single doc) and DELETE. This will enable nice cacheable paths to access single items.

Example

GET /api/documents/v1/mycollection/23324 -> Returns entire document
DELETE /api/documents/v1/mycollection/23324 -> Delete this document
PUT /api/documents/v1/mycollections/23324 -> Update this document
POST /api/documents/v1/mycollection - Add document(s) to a specific collection
Search:  GET /api/documents/v1/mycollection/_search  (returns ID's)

Also, I think the "rest" style API should be documented using cURL, like Elasticsearch does.

**Comment by sigdestad** [comment]
version should also be moved to root, like /api/v1/documents...

**Comment by ComLock** [comment]
Since that API existed in Explorer 1.5.0 I suppose these changes are "breaking" enough that we should call it "v2" now.

**Comment by ComLock** [comment]
Maybe we need both PATCH and PUT rather than the Partial Boolean query param
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by ComLock** [comment]
Unfortunately this https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/ expired 13 May 2022 https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html

**Comment by ComLock** [comment]
Since the "Fetch API Standard" doesn't support GET with a payload body, the search endpoint must use POST.
Which might also be correct, as caching search results in proxies, seems like a waste.


Since both creating and searching uses POST, then those functions must be available on different endpoints.


Not sure I like the "_search" path though.

**Comment by ComLock** [comment]
My suggestion:

```
Batch:
POST   api/v2/documents/mycollection        Create or update document(s) - Payload in body
POST   api/v2/documents/mycollection/query  Search document(s) - Only return ids, or full document? - Params in json body
GET    api/v2/documents/mycollection        Retrieve document(s) by id - url query param ?id=1&id=2  ?ids=1,2

Single:
GET    api/v2/documents/mycollection/1234   Retrieve document - No params
PUT    api/v2/documents/mycollection/1234   Full replace document - Payload in body
PATCH  api/v2/documents/mycollection/1234   Partial modify document - Payload in body
DELETE api/v2/documents/mycollection/1234   Delete document - No params
```

**Comment by ComLock** [comment]
After discussion we ended up with:

```
Batch:
POST   api/v2/documents/mycollection        Create or update document(s) - Payload in body
POST   api/v2/documents/mycollection/query  Search document(s) - Return full document - Params in json body
GET    api/v2/documents/mycollection        Retrieve document(s) by id - url query param ?id=1&id=2
DELETE api/v2/documents/mycollection        Delete document(s) by id - url query param ?id=1&id=2

Single:
GET    api/v2/documents/mycollection/1234   Retrieve document - No params
PUT    api/v2/documents/mycollection/1234   Full replace document - Payload in body
PATCH  api/v2/documents/mycollection/1234   Partial modify document - Payload in body
DELETE api/v2/documents/mycollection/1234   Delete document - No params
```

And in the future

```
POST   api/v2/documents/*/query          Search document(s) across collections - Only return collection and ids, or full document? - Params in json body
_id
_collection // Always send in results
`
``
