### ISSUE TITLE
Hiding the default interface

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#811]
To avoid confusion, we'll completely hide the default interface:

* On home page, when searching "all collections" - hide the graphQL icon (so, it should only be visible if an interface is selected)
* Also, when working in the API testing UI, prevent selecting "All collections/default interface" (basically, one must always select an interface)
* In the application key UI, hide the default interface so it cannot be used in an app key

**Comment by ComLock** [comment]
- [ ] Make sure /api/graphql doesn't work even though an api-key has default interface
- [ ] Make data migration to remove default interface from existing api-keys
