### ISSUE TITLE
Remaining bugs before 2.0 release

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-explorer#837]
These bugs were identified with the snapshot from July 6th, running on XP 7.13.0

## Things we should fix

- [x] #839
- [x] #840
- [x] #842
- [x] #841
- [x] The Rest API has a web interface, but it is not possible to use it. http://localhost:8080/webapp/com.enonic.app.explorer/documents/api/v1 returns admin login page, and guest user is not working. Can we drop the 401 handling on the root page maybe?
- [x] API path should be changed to /..explorer/api/v1/documents
- [x] For consistency, move graphQL API to /..explorer/api/graphql as well

## Rest API

Up for discussion, what do we do about these things?

- [x] Had a very hard time trying to use the API, basically we need examples with cURL, not Enonic controllers
- [x] API mixes JSON and regular param values. Har to use and document. Maybe use a JSON body approach instead - like ES?
- [x] API apparently not using "RESTful" approach, i.e. access documents on /mycollection/ID, PUT/DELETE on same path etc.

## Starter
The starter project is located in the repo starter-collector. I have moved the custom collector docs to this repo, setup a corresponding doc page in the dev portal, but both starter and doc need to be up2date

- [x] Update starter
- [x] Update the starter docs (copy initial steps from another guide)

## Nice to fix

- [x] #849

**Comment by ComLock** [comment]
> When clicking the "download" icon on a collection,randomly it turns into a spinning ?
This happens because of the delay of starting a task. This was done in order to deny starting the same download more than once at the same time. There is a worse "bug" here, you actually can't start the same download before the task, drops out of the taskList. Which can be like a minute or more?

**Comment by ComLock** [comment]
> Testing the interface search, the result shows a blank page (Firefox) - Change so it link to the Home page with interface as a parameter instead?

Chrome and Firefox looks the same, for some reason the _alltext column is missing.
I'm not sure I like leaving the page, clicking a menu-item or link should be consistently different than clicking an UI button?

![Image](https://github.com/enonic/app-explorer/assets/118847/a1d18e4f-5417-42c2-9dce-0dd7dab3b3d9)

**Comment by ComLock** [comment]
> The Rest API has a web interface, but it is not possible to use it. http://localhost:8080/webapp/com.enonic.app.explorer/documents/api/v1 returns admin login page, and guest user is not working. Can we drop the 401 handling on the root page maybe?

You have to use a browser extention like ModHeader to set the authentication header.

We can drop the 401 on the root /api/v2/documents , but not on children, or one could use the api to find collection/repo names.
